spring:
  config:
    import: "kubernetes:"
  application:
    name: metadata-backend
  cloud:
    kubernetes:
      secrets:
        enabled: true
        paths:
          - /etc/metadata-secret
          - /etc/eventhub-secret
          - /etc/meta-json-schema
      config:
        paths:
          - /etc/application/application.yml
        enable-api: false
      reload:
        enabled:
          false