apiVersion: v1
kind: ServiceAccount
metadata:
 name: metadata-account
 namespace: backend
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metadata-namespace-reader-binding
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: metadata-account
    namespace: backend
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: ""